[travis] add coverage test to .travis.yml
[travis] dont build debug unit tests

[travis] fix typo

[travis] upload coverage report to codecov.io

[travis] upload coverage report to codecov.io

[travis] upload coverage report to codecov.io

[travis] remove codecov.io support for now

[travis] use gcov-7 on travis

[travis] report to codecov.io

[travis] add comment what we do in install

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -15,7 +15,7 @@ linux-gcc-7: &linux-gcc-7
   addons:
     apt:
       sources: ['ubuntu-toolchain-r-test']
-      packages: ['g++-7']
+      packages: ['g++-7', 'lcov']
   before_install:
     - export CC="gcc-7" CXX="g++-7"
 
@@ -40,10 +40,12 @@ matrix:
     env:
       - BUILD=unit
       - BUILD_TYPE=Release
-  - << : *linux-gcc-7
-    env:
-      - BUILD=unit
-      - BUILD_TYPE=Debug
+  # To reduce build time we disable debug builds of unit tests, because they
+  # are completely contained in coverage test.
+  # - << : *linux-gcc-7
+  #   env:
+  #     - BUILD=unit
+  #     - BUILD_TYPE=Debug
   - << : *linux-gcc-7
     env:
       - BUILD=performance
@@ -74,28 +76,49 @@ matrix:
        - tar -C /tmp/ -zxvf /tmp/doxygen-download/${DOXYGEN_VER}.linux.bin.tar.gz
        - PATH=$PATH:/tmp/${DOXYGEN_VER}/bin/
        - doxygen --version
+  - << : *linux-gcc-7
+    env:
+      - BUILD=coverage
+      - BUILD_TYPE=Debug
 
 install:
   - ccache --version
   - $CXX -v
   - cmake --version
+  - |
+    # use gcov7 matching the g++7 compiler
+    if [[ "${BUILD}" =~ ^(coverage)$ ]]; then
+      GCOV_PATH=`realpath ~/bin`
+      mkdir -p ${GCOV_PATH}
+      ln -s `which gcov-7` ${GCOV_PATH}/gcov
+      export PATH="${GCOV_PATH}:${PATH}"
+    fi
 
 before_script:
   - mkdir ../seqan3-build
   - cd ../seqan3-build
   - cmake ../seqan3/test/${BUILD} -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
   - |
-    if test unit = "${BUILD}" || test header = "${BUILD}" || test snippet = "${BUILD}"; then
+    if [[ "${BUILD}" =~ ^(unit|header|snippet|coverage)$ ]]; then
       make gtest_project
     fi
   - |
-    if test performance = "${BUILD}"; then
+    if [[ "${BUILD}" =~ ^(performance)$ ]]; then
       make gbenchmark_project
     fi
 
 script:
   - make -k
-  - ctest . --output-on-failure
+  - |
+    if test coverage != "${BUILD}"; then
+      ctest . --output-on-failure
+    fi
+
+after_success:
+  - |
+    if test coverage = "${BUILD}"; then
+      bash <(curl -s https://codecov.io/bash) -f ./seqan3_coverage -R "${TRAVIS_BUILD_DIR}" || echo 'Codecov failed to upload'
+    fi
 
 after_script:
   - ccache -s
